### ISSUE TITLE
Argument mixups

### ISSUE THREAD

**Issue by daigo75** [XeroAPI/XeroOAuth-PHP#30]
Class `XeroOAuth` expects arguments `access_token` and `access_token_secret`, while class OAuthSimple expects `consumer_key` and `shared_secret`. This must be tidied up, the examples are confusing enough without this "renaming" through the code.

**Comment by ronanq** [comment]
I'm not sure what the issue here is - OAuthsimple is wrapped by the XeroOAuth class so unless you want to go digging into it, there shouldn't be any confusion here. If you do wish to have a deeper dive, then yes, that is a cost of doing so, but not a compelling reason for changing the code as far as I can see it.

There are also three different OAuth implementations supported - you seem to be looking at the private type - your assertions do not hold true for other types.

That said, if you want to give some examples referencing specific code blocks that you think are problematic, I would be happy to take a look.

**Comment by ronanq** [comment]
Will assume this can be closed for now, but feel free to reply if you have some more details....
